# Generated by Django 4.2.17 on 2025-02-16 11:42

import django.contrib.postgres.fields
from django.db import migrations, models
import homeBuild.accounts.models.app_profile


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_groups_appuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='job_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('renovation', 'Renovation'), ('maintenance', 'Maintenance'), ('landscaping', 'Landscaping'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=30), blank=True, default=homeBuild.accounts.models.app_profile.JobCategory, size=None),
        ),
    ]
