# Generated by Django 4.2.17 on 2025-02-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_contractorprofile_job_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorprofile',
            name='available_status',
        ),
    ]
