# Generated by Django 4.2.17 on 2025-02-16 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_contractorprofile_available_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='job_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('renovation', 'Renovation'), ('maintenance', 'Maintenance'), ('landscaping', 'Landscaping'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=30), blank=True, default='other', size=None),
        ),
    ]
