# Generated by Django 4.2.17 on 2025-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_contractorprofile_job_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('renovation', 'Renovation'), ('maintenance', 'Maintenance'), ('landscaping', 'Landscaping'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='contractorprofile',
            name='job_categories',
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='job_categories',
            field=models.ManyToManyField(blank=True, to='accounts.jobcategory'),
        ),
    ]
