# Generated by Django 4.2.17 on 2025-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_appuser_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
