# Generated by Django 4.2.17 on 2025-02-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='project',
            new_name='to_project',
        ),
    ]
