# Generated by Django 4.2.17 on 2025-03-13 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_jobcategory_remove_contractorprofile_job_categories_and_more'),
        ('photos', '0005_alter_photo_project_alter_photo_user'),
        ('common', '0004_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date_of_publication', models.DateTimeField(auto_now_add=True)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('job_category', models.ForeignKey(blank=True, default='other', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.jobcategory')),
                ('photos', models.ManyToManyField(blank=True, related_name='jobs', to='photos.photo')),
            ],
        ),
    ]
