# Generated by Django 4.2.17 on 2025-03-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='homeowner',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='photos',
        ),
    ]
