# Generated by Django 4.2.17 on 2025-03-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('common', '0008_remove_job_homeowner_remove_job_job_category_and_more'),
        ('photos', '0007_alter_photo_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='message',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.job'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
