# Generated by Django 4.2.17 on 2025-02-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_alter_project_address_alter_project_description'),
        ('photos', '0002_remove_photo_description_remove_photo_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
