# Generated by Django 4.2.17 on 2025-03-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('photos', '0006_photo_job_alter_photo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_photos', to='jobs.job'),
        ),
    ]
