# Generated by Django 4.2.17 on 2025-04-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='job',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='project',
        ),
    ]
