# Generated by Django 4.2.17 on 2025-02-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_jobcategory_remove_contractorprofile_job_categories_and_more'),
        ('projects', '0002_alter_project_address_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.contractorprofile'),
            preserve_default=False,
        ),
    ]
